#!/usr/bin/env bash
# Install and configure HAproxy (Load balancer)
# To distribute traffics to 2 webservers
# Using roundrobin algorithm
apt update -y
apt install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy
my_server_config=\
"
frontend haproxy-main
	bind *:80
	option forwardfor
	default_backend nginx_servers

backend nginx_servers
	balance roundrobin
	server 530603-web-01 54.85.31.112:80 check
	server 530603-web-02 54.173.67.127:80 check
"
echo "$my_server_config" >> /etc/haproxy/haproxy.cfg

service haproxy restart
